# Site settings
title: arXiv Benchmark
email: korzen@cs.uni-freiburg.de
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# The subpath of your site, e.g. /blog
baseurl: "/arxiv-benchmark"

# The base hostname & protocol for your site, e.g. http://example.com
url: "localhost:4000" 

# twitter_username: jekyllrb
github_username: ckorzen

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
